version: '3.4'

services:
    backendtest:
        image: periscopebackend
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
            MONGO_URL: mongodb://mongodb:27017
            PORT:
        ports:
            - 4111:4111
    mongodb:
        image: mongo:7.0.3
        ports:
            - '27017:27017'
